# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from ._models import CloudInitiatedRollbackPolicy
from ._models import CloudInitiatedRollbackPolicyFailure
from ._models import ContractModel
from ._models import Counters
from ._models import Deployment
from ._models import DeploymentDeviceState
from ._models import DeploymentStatus
from ._models import Device
from ._models import DeviceClass
from ._models import DeviceClassProperties
from ._models import DeviceClassSubgroup
from ._models import DeviceClassSubgroupDeployment
from ._models import DeviceClassSubgroupDeploymentStatus
from ._models import DeviceClassSubgroupUpdatableDevices
from ._models import DeviceHealth
from ._models import DeviceOperation
from ._models import DeviceUpdateAgentId
from ._models import Error
from ._models import FileImportMetadata
from ._models import Group
from ._models import HealthCheck
from ._models import ImportManifestMetadata
from ._models import ImportUpdateInputItem
from ._models import InlineStep
from ._models import InnerError
from ._models import InstallResult
from ._models import Instructions
from ._models import Limits
from ._models import LogCollection
from ._models import LogCollectionOperationDetailedStatus
from ._models import LogCollectionOperationDeviceStatus
from ._models import ReferenceStep
from ._models import Step
from ._models import StepResult
from ._models import Update
from ._models import UpdateCompliance
from ._models import UpdateFile
from ._models import UpdateFileBase
from ._models import UpdateFileDownloadHandler
from ._models import UpdateId
from ._models import UpdateInfo
from ._models import UpdateOperation
from ._models import UsageQuotaCounter

from ._enums import DeploymentState
from ._enums import DeviceClassSubgroupDeploymentState
from ._enums import DeviceDeploymentState
from ._enums import DeviceHealthState
from ._enums import GroupType
from ._enums import HealthCheckResult
from ._enums import ImportType
from ._enums import OperationStatus
from ._enums import StepType
from ._patch import __all__ as _patch_all
from ._patch import *  # pylint: disable=unused-wildcard-import
from ._patch import patch_sdk as _patch_sdk

__all__ = [
    "CloudInitiatedRollbackPolicy",
    "CloudInitiatedRollbackPolicyFailure",
    "ContractModel",
    "Counters",
    "Deployment",
    "DeploymentDeviceState",
    "DeploymentStatus",
    "Device",
    "DeviceClass",
    "DeviceClassProperties",
    "DeviceClassSubgroup",
    "DeviceClassSubgroupDeployment",
    "DeviceClassSubgroupDeploymentStatus",
    "DeviceClassSubgroupUpdatableDevices",
    "DeviceHealth",
    "DeviceOperation",
    "DeviceUpdateAgentId",
    "Error",
    "FileImportMetadata",
    "Group",
    "HealthCheck",
    "ImportManifestMetadata",
    "ImportUpdateInputItem",
    "InlineStep",
    "InnerError",
    "InstallResult",
    "Instructions",
    "Limits",
    "LogCollection",
    "LogCollectionOperationDetailedStatus",
    "LogCollectionOperationDeviceStatus",
    "ReferenceStep",
    "Step",
    "StepResult",
    "Update",
    "UpdateCompliance",
    "UpdateFile",
    "UpdateFileBase",
    "UpdateFileDownloadHandler",
    "UpdateId",
    "UpdateInfo",
    "UpdateOperation",
    "UsageQuotaCounter",
    "DeploymentState",
    "DeviceClassSubgroupDeploymentState",
    "DeviceDeploymentState",
    "DeviceHealthState",
    "GroupType",
    "HealthCheckResult",
    "ImportType",
    "OperationStatus",
    "StepType",
]
__all__.extend([p for p in _patch_all if p not in __all__])
_patch_sdk()
